device: 'cuda'
gpu_id: 0

# disable_reweight: false
lr: 0.0001
momentum: 0.9
weight_decay: 0.0005
dropout_rate: 0.3
seed: 1

use_wandb: false
wandb_project: 'vad'
wandb_entity:
wandb_run_name:
wandb_group:
wandb_tags: []

use_pruning: false
prune_magnitude_ratio: 0.05
prune_random_ratio: 0.05
use_early_unprune: false
unprune_ratio: 0.3
prune_random_seed:

epochs: 200
batch_size: 30
test_freq: 1
segment_len: 16
process_len: 32
feature_dim: 2048

r: 0.2   # abnormal ratio (pseudo-label)
h: 0.2   # high confidence normal videos ratio

sample_type: 'uniform'

logger_path: './logger'
ckpt_path: './ckpts'
pretrained_path:

dataset: 'ipad'
feature_path: './data/IPAD/features'
anno_root: './data/IPAD'
training_split: './data/IPAD/lanp_train_split.txt'
testing_split: './data/IPAD/test_split.txt'
np_scores_path:
feature_name_end: '_res.npy'
disable_reweight: true  # IPAD에서는 리웨이트 끄는 편이 더 나은 결과를 보여 설정을 기본 비활성화

th_auc: 0.75
th_pr: 0.5
