device: 'cuda'
gpu_id: 0

lr: 0.0001
momentum: 0.9
weight_decay: 0.0005
dropout_rate: 0.7
seed: 1

use_wandb: false
wandb_project: 'vad'
wandb_entity:
wandb_run_name:
wandb_group:
wandb_tags: []

use_pruning: false
prune_magnitude_ratio: 0.05
prune_random_ratio: 0.05
use_early_unprune: false
unprune_ratio: 0.3
prune_random_seed:

epochs: 300
batch_size: 30
test_freq: 1
segment_len: 16
process_len: 32
feature_dim: 2048

r: 0.4 # abnormal ratio
h: 0.1 # high confidence normal videos ratio

sample_type: 'uniform'

logger_path: './logger'
ckpt_path: './ckpts'
pretrained_path:

dataset: 'sttad'
frames_root: './data/STTAD/rgb-images'
feature_path: './data/STTAD/features'
anno_path: './data/STTAD/labels'
training_split: './data/STTAD/trainlist.txt'
testing_split: './data/STTAD/testlist.txt'
np_scores_path:
feature_name_end: '_res.npy'

th_auc: 0.5
th_pr: 0.25
